name: Show Me the S3cr3tz
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ghtoken: ${{ secrets.ghrs_github_api_token }}
      run: |
        echo $ghtoken >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
